apiVersion: v1
kind: Service
metadata:
  name: grafana-admission-webhook
  labels:
    app: admission-webhook
spec:
  ports:
    - port: 443
      targetPort: 7443
  selector:
    name: grafana-operator