apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: grafanadatasources.monitor.kun
spec:
  group: monitor.kun
  names:
    kind: GrafanaDataSource
    listKind: GrafanaDataSourceList
    plural: grafanadatasources
    singular: grafanadatasource
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          required: ["datasources", "name"]
          properties:
            name:
              type: string
              minimum: 1
            datasources:
              type: array
              items:
                description: Grafana Datasource Object
                type: object
        status:
          type: object
